apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
   repoURL: git@github.com:timmhirsens/gitops-demo.git
   targetRevision: HEAD
   path: gitops/apps
   directory:
     recurse: true
  destination:
   server: https://kubernetes.default.svc
   namespaces: argocd
  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

