---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.21.4
    helm:
      releaseName: trivy-operator

  destination:
    server: "https://kubernetes.default.svc"
    namespace: trivy-operator

  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

