---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-website
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/timmhirsens/gitops-demo-team-website.git
    targetRevision: HEAD
    path: apps

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
