---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
   repoURL: git@github.com:timmhirsens/gitops-demo.git
   targetRevision: HEAD
   path: gitops/manifests/website

  destination:
    server: "https://kubernetes.default.svc"
    namespace: website

  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

